### ISSUE TITLE
This is spammed in console

### ISSUE THREAD

**Issue by Ethanial** [SirFaizdat/Prison#122]
The following message is spammed in console, how do i fix the exception?

[22:59:01 WARN]: [Prison] Task #10 for Prison vv2.1.6 Emergency Patch generated an exception
java.lang.NullPointerException
        at me.sirfaizdat.prison.ranks.BalanceChangeListener$1.run(BalanceChangeListener.java:38) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]

**Comment by SirFaizdat** [comment]
Either Vault or an economy plugin is missing, or out of date. Try updating both.

**Comment by SirFaizdat** [comment]
Closing for inactivity (it's been 2 months), please reopen if the problem persists.
