### ISSUE TITLE
cant add rank

### ISSUE THREAD

**Issue by Itzcosmic** [SirFaizdat/Prison#134]
When i do /prisonranks add A 0 A it says '[17:39:56 INFO]: Itzcosmicgaming issued server command: /prisonranks add A 0 A
[17:39:56 INFO]: [Prison] There was an error handling command prisonranks. Reason: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
[17:39:56 INFO]: [Prison] More info: 
[17:39:56 WARN]: ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
[17:39:56 WARN]: 	at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:405)
[17:39:56 WARN]: 	at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getGroups(Permission_PermissionsEx.java:372)
[17:39:56 WARN]: 	at me.sirfaizdat.prison.ranks.Ranks.isRank(Ranks.java:537)
[17:39:56 WARN]: 	at me.sirfaizdat.prison.ranks.cmds.CmdAddRank.execute(CmdAddRank.java:29)
[17:39:56 WARN]: 	at me.sirfaizdat.prison.core.Command.run(Command.java:75)
[17:39:56 WARN]: 	at me.sirfaizdat.prison.core.AbstractCommandManager.onCommand(AbstractCommandManager.java:48)
[17:39:56 WARN]: 	at me.sirfaizdat.prison.ranks.cmds.RanksCommandManager.onCommand(RanksCommandManager.java:83)
[17:39:56 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:39:56 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:39:56 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[17:39:56 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[17:39:56 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[17:39:56 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:39:56 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:39:56 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[17:39:56 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:39:56 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:39:56 WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[17:39:56 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[17:39:56 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[17:39:56 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[17:39:56 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
'

**Comment by SirFaizdat** [comment]
The error message says that something is wrong with PermissionsEx.

**Comment by Itzcosmic** [comment]
ok ill check

**Comment by Itzcosmic** [comment]
and its enabled

**Comment by Itzcosmic** [comment]
ill do a fresh re download and checkif it works

**Comment by Itzcosmic** [comment]
now it says 'rank does not exist'

**Comment by Itzcosmic** [comment]
its the same thing again

**Comment by Itzcosmic** [comment]
here are all perms:
  A:
    worlds:
      A:
        options:
          prefix: '&b'
    options:
      prefix: '&f[&bA&f]'
    permissions:
    - essentials.warp
    - essentials.warp.A
    - essentails.warp
    - essentails.warp.a
    - essentials.bal
    - essentials.spawn
    - essentials.abn.notify
    - essentials.mute.notify
    - essentials.msg
    - essentials.sethome.multiple.players
    - essentials.mail
    - essentials.mail.send
    - essentials.signs.use.time
    - essentials.signs.use.balance
    - essentials.signs.use.weather
    - essentials.signs.use.enchant
    - essentials.signs.use.buy
    - essentials.signs.use.sell
    - essentials.pay
    - essentials.warp.list
    - essentials.back
    - essentials.spawn
    - essentials.rules
    - essentials.motd
    - essentials.list
    - essentials.help
    - essentials.sethome
    - essentials.delhome
    - essentials.home
    - essentials.tpaccept
    - essentials.balance
    - essentials.balancetop
    - essentials.tpa
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.kits.A
    - essentials.kit
    - -bukkit.command.me
    - -bukkit.command.give
    - -bukkit.command.plugins
    - autosell.toggle
    - autosell.sellall
    - autosell.shop.A
    - autosell.signs.sell
    - autosell.signs.see.A
    - essentials.warp
    - essentials.warps
    inheritance: []
  B:
    inheritance:
    - A
  options:
    prefix: '&f[&bB&f]’
    permissions:
    - essentials.warp.B
    -essentials.kits.B
C:
options:
    prefix: '&f[&bC&f]’
    inheritance:
    - B
    permissions:
    - essentials.warp.C
    -essentials.kits.C
D:
options:
    prefix: '&f[&bC&f]’
    inheritance:
    - C
    permissions:
    - essentials.warp.D
    -essentials.kits.D

**Comment by SirFaizdat** [comment]
Make sure that you have the latest version of Vault and PermissionsEx.

**Comment by Itzcosmic** [comment]
i do

**Comment by Itzcosmic** [comment]
XD

**Comment by SirFaizdat** [comment]
The error message says something is wrong with Vault's connection to PermissionsEx. There must be something wrong there, perhaps PermissionsEx has a corrupted file?

**Comment by Itzcosmic** [comment]
no i redowloaded it today

**Comment by Itzcosmic** [comment]
[pex.zip](https://github.com/SirFaizdat/Prison/files/160367/pex.zip)

**Comment by Itzcosmic** [comment]
check if there is

**Comment by Itzcosmic** [comment]
?

**Comment by Itzcosmic** [comment]
so...?

**Comment by SirFaizdat** [comment]
Your permissions.yml is full of parse errors, all over the place. Paste the contents of it into [YAML Lint](http://yamllint.com) and follow the error messages until the file is cleaned.

**Comment by Itzcosmic** [comment]
god the website is soooo annoying

**Comment by Itzcosmic** [comment]
please say you have a alternate

**Comment by Itzcosmic** [comment]
it said this:
(<unknown>): did not find expected key while parsing a block mapping at line 1 column 1 
line 1 is:
Groups:
whats wrong with that?

**Comment by Itzcosmic** [comment]
sorry im not a pro at coding =/

**Comment by SirFaizdat** [comment]
No worries, I'll fix it up for you when I get home.

**Comment by Itzcosmic** [comment]
ok thanks

**Comment by Itzcosmic** [comment]
so how are you? Are you comfy in your home?

**Comment by Itzcosmic** [comment]
ba dum tss

**Comment by Itzcosmic** [comment]
helllllooooo??

**Comment by SirFaizdat** [comment]
Here's your brand new, formatted permissions.yml file. Just put this in, in place of your current permissions.yml file.

http://hastebin.com/asikecolup.avrasm
