### ISSUE TITLE
Problem with loading the plugin

### ISSUE THREAD

**Issue by soren913a** [SirFaizdat/Prison#137]
I get this error all the time when performing a prison command why do i get it ?

[00:41:22 WARN]: [Prison] Task #12 for Prison vv2.1.6 Emergency Patch generated an exception
java.lang.NullPointerException
        at me.sirfaizdat.prison.ranks.BalanceChangeListener$1.run(BalanceChangeListener.java:38) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8.jar:git-Spigot-6c9b0a1-de5c261]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by SirFaizdat** [comment]
Either you do not have an economy plugin installed, or the economy plugin isn't registering a balance for that player.

**Comment by soren913a** [comment]
i have vault installed.

**Comment by SirFaizdat** [comment]
Do you have an economy plugin installed?

**Comment by soren913a** [comment]
i only have vault installed, prison, world edit installed atm

**Comment by SirFaizdat** [comment]
Vault is merely a bridge between your economy and permissions plugins, and Prison. You must have an economy and permissions plugin installed. For economy, I recommend [EssentialsX](https://www.spigotmc.org/resources/essentialsx.9089/) (which contains 100+ commands as well as an economy system) and for permissions, I recommend [PermissionsEx](http://dev.bukkit.org/bukkit-plugins/permissionsex/).

**Comment by SirFaizdat** [comment]
Closing for inactivity, reopen if the problem persists.
