### ISSUE TITLE
Ranking Issues

### ISSUE THREAD

**Issue by Asticol** [SirFaizdat/Prison#141]
Hello, SirFaizdat.

Recently, I've tried setting up a Prison server, and it was quite easy to do (thanks for making it simple for a Smart Alec like me.)
I tried setting up ranks via PermissionsEx (see here for the permissions: http://hastebin.com/emexomanav.sm) but I get the message "There was an error in starting ranks. Check the console for details." 
I check the console and I see this: http://hastebin.com/jabizozoka.avrasm

Any help figuring this out?

Much appreciated,
- John

**Comment by SirFaizdat** [comment]
It appears that PermissionsEx is either outdated, inaccessible (disabled),
or otherwise impaired.

**Comment by Asticol** [comment]
Updated to the recent PermissionsEX, still gives me the same issue. It's enabled, as me and my friend are in new testing rank.

In what way could it be impaired? (Sorry if the previous statement came across as 'pushy' or mean, but I couldn't have phrased it better)

**Comment by SirFaizdat** [comment]
Is Vault updated to the latest version? If so, can you tell me what /vault-info prints out?

**Comment by Asticol** [comment]
Heres the Log from starting the server to inputting the command: http://hastebin.com/lalifihere.vbs

**Comment by SirFaizdat** [comment]
The log file says that PermissionsEx is disabling. 

02.05 04:56:55 [Server] INFO Disabling PermissionsEx v1.23.4

**Comment by Asticol** [comment]
How would I enable this?

**Comment by SirFaizdat** [comment]
```yaml
02.05 04:56:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
02.05 04:56:55 [Server] INFO Caused by: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
02.05 04:56:55 [Server] INFO in 'string', line 8, column 13:
02.05 04:56:55 [Server] INFO Unassigned:
02.05 04:56:55 [Server] INFO ^
02.05 04:56:55 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx-1.23.4.jar:?]
02.05 04:56:55 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx-1.23.4.jar:?]
02.05 04:56:55 [Server] INFO at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx-1.23.4.jar:?]
02.05 04:56:55 [Server] INFO ... 23 more
02.05 04:56:55 [Server] INFO Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
02.05 04:56:55 [Server] INFO in 'string', line 8, column 13:
02.05 04:56:55 [Server] INFO Unassigned:
02.05 04:56:55 [Server] INFO ^
02.05 04:56:55 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at ru.tehkode.permissions.backends.file.FileConfig.loadFromString(FileConfig.java:68) ~[PermissionsEx-1.23.4.jar:?]
02.05 04:56:55 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[Spigot-1.9.2.jar:git-Spigot-944aa20-8d16fc0]
02.05 04:56:55 [Server] INFO at ru.tehkode.permissions.backends.file.FileConfig.load(FileConfig.java:38) ~[PermissionsEx-1.23.4.jar:?]
02.05 04:56:55 [Server] INFO at ru.tehkode.permissions.backends.file.FileBackend.reload(FileBackend.java:309) ~[PermissionsEx-1.23.4.jar:?]
02.05 04:56:55 [Server] INFO ... 23 more
02.05 04:56:55 [Server] INFO Disabling PermissionsEx v1.23.4
```

There's the full stack trace. Could you send me your permissions.yml?

**Comment by SirFaizdat** [comment]
Something is definitely wrong with PermissionEx which is preventing it from starting up successfully. It is most likely an issue with its `permissions.yml` or `config.yml` - use [YAML Lint](http://www.yamllint.com/) to ensure that these files are using the proper format.

**Comment by SirFaizdat** [comment]
Closing for 1 week inactivity - reopen if problem persists.

_**Note:** I shortened the inactivity time from 1 month to 1 week because I must make more time to work on [Prison 3.0](https://github.com/sirfaizdat/prison/tree/3.0)._
