### ISSUE TITLE
ClassNotFoundException with 2.2.3

### ISSUE THREAD

**Issue by RoboMWM** [SirFaizdat/Prison#186]
So, turns out, even when downloading the build either from spigot or from Github releases, I'm getting this stacktrace now :/

```
[19:53:39] [Server thread/INFO]: [Prison] Enabling Prison v2.2.3
[19:53:39] [Server thread/INFO]: [0;33;22m[[0;31;22mPrison[0;33;22m] [0;31;1mAn unexpected error occured. Check to make sure your copy of the plugin is not corrupted.[m
[19:53:39] [Server thread/WARN]: java.lang.ClassNotFoundException: me.sirfaizdat.prison.mines.Block
[19:53:39] [Server thread/WARN]:    at java.net.URLClassLoader.findClass(Unknown Source)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[19:53:39] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.lang.Class.forName0(Native Method)
[19:53:39] [Server thread/WARN]:    at java.lang.Class.forName(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.resolveClass(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readClassDesc(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject0(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.util.HashMap.readObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:53:39] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:53:39] [Server thread/WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.lang.reflect.Method.invoke(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readSerialData(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject0(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readSerialData(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject0(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.mines.MinesManager.load(MinesManager.java:79)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.mines.MinesManager.<init>(MinesManager.java:51)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.mines.Mines.enable(Mines.java:62)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.core.Prison.enableMines(Prison.java:195)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.core.Prison.initComponents(Prison.java:113)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.core.Prison.onEnable(Prison.java:80)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[19:53:39] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:375)
[19:53:39] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:325)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:418)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:383)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:329)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:275)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:584)
[19:53:39] [Server thread/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:53:39] [Server thread/INFO]: [0;33;22m[[0;31;22mPrison[0;33;22m] [0;31;1mAn unexpected error occured. Check to make sure your copy of the plugin is not corrupted.[m
[19:53:39] [Server thread/WARN]: java.lang.ClassNotFoundException: me.sirfaizdat.prison.mines.Block
[19:53:39] [Server thread/WARN]:    at java.net.URLClassLoader.findClass(Unknown Source)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[19:53:39] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.lang.Class.forName0(Native Method)
[19:53:39] [Server thread/WARN]:    at java.lang.Class.forName(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.resolveClass(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readClassDesc(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject0(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.util.HashMap.readObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:53:39] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:53:39] [Server thread/WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.lang.reflect.Method.invoke(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readSerialData(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject0(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readSerialData(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject0(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.mines.MinesManager.load(MinesManager.java:79)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.mines.MinesManager.<init>(MinesManager.java:51)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.mines.Mines.enable(Mines.java:62)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.core.Prison.enableMines(Prison.java:195)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.core.Prison.initComponents(Prison.java:113)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.core.Prison.onEnable(Prison.java:80)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[19:53:39] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:375)
[19:53:39] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:325)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:418)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:383)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:329)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:275)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:584)
[19:53:39] [Server thread/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:53:39] [Server thread/INFO]: [0;33;22m[[0;31;22mPrison[0;33;22m] [0;31;1mAn unexpected error occured. Check to make sure your copy of the plugin is not corrupted.[m
[19:53:39] [Server thread/WARN]: java.lang.ClassNotFoundException: me.sirfaizdat.prison.mines.Block
[19:53:39] [Server thread/WARN]:    at java.net.URLClassLoader.findClass(Unknown Source)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[19:53:39] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.lang.Class.forName0(Native Method)
[19:53:39] [Server thread/WARN]:    at java.lang.Class.forName(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.resolveClass(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readClassDesc(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject0(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.util.HashMap.readObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:53:39] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:53:39] [Server thread/WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.lang.reflect.Method.invoke(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readSerialData(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject0(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readSerialData(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject0(Unknown Source)
[19:53:39] [Server thread/WARN]:    at java.io.ObjectInputStream.readObject(Unknown Source)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.mines.MinesManager.load(MinesManager.java:79)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.mines.MinesManager.<init>(MinesManager.java:51)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.mines.Mines.enable(Mines.java:62)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.core.Prison.enableMines(Prison.java:195)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.core.Prison.initComponents(Prison.java:113)
[19:53:39] [Server thread/WARN]:    at me.sirfaizdat.prison.core.Prison.onEnable(Prison.java:80)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[19:53:39] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[19:53:39] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:375)
[19:53:39] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:325)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:418)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:383)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:329)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:275)
[19:53:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:584)
[19:53:39] [Server thread/WARN]:    at java.lang.Thread.run(Unknown Source)
```

**Comment by RoboMWM** [comment]
I hope the latest commit wasn't messing around with data files...

**Comment by Camouflage100** [comment]
Thank you for submitting the issue. I'll look into it as soon as I have time!

**Comment by RoboMWM** [comment]
So it did mess around with data files, and idk how to fix it since you guys store a serialized version of whatever you're storing :/

**Comment by Camouflage100** [comment]
In Prison 2.3 Mines and Ranks will no longer be serialized. I've already started working on that. What's causing your problem is when I was working on 2.2.3, I re-arranged the file tree of the project. The only thing I can recommend for now is to revert to 2.2.2 and use that version until 2.3 comes out with a fix.

**Comment by SirFaizdat** [comment]
Perhaps it would be wise to do an emergency patch, v2.2.4, to fix this problem. As long as the fully qualified names are the same, the files will load.

**Comment by RoboMWM** [comment]
Yea, the data structure is the same - just the data files appear to be serialized differently (less line spaces in the "broken" data files it seems).

**Comment by RoboMWM** [comment]
[mines.zip](https://github.com/SirFaizdat/Prison/files/548696/mines.zip)

`d.mine` was one that was converted by 321e7846dc6c70aef18a737b57a4f5278118b86e, while `E.mine` is one that's created with 2.2.3

**Comment by SirFaizdat** [comment]
Perhaps it would be wise to do an emergency patch, v2.2.4, to fix this
problem. As long as the fully qualified names are the same, the files will
load.

Regards,
Faizaan Datoo
fdatoo7@gmail.com
