### ISSUE TITLE
Error spamming in console

### ISSUE THREAD

**Issue by TroyTroy** [SirFaizdat/Prison#61]
[Server thread/WARN]: [Prison] Task #60 for Prison v2.1.0.1 generated an exception
java.lang.NoSuchMethodError: net.milkbowl.vault.economy.Economy.getBalance(Lorg/bukkit/OfflinePlayer;)D
at me.sirfaizdat.prison.ranks.BalanceChangeListener$1.run(BalanceChangeListener.java:38) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-13716d9-0899683]
at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-13716d9-0899683]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot.jar:git-Spigot-13716d9-0899683]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-13716d9-0899683]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-13716d9-0899683]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-13716d9-0899683]
at java.lang.Thread.run(Thread.java:722) [?:1.7.0_17]

**Comment by SirFaizdat** [comment]
Update your Vault and try again
