### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Toshka17** [SirFaizdat/Prison#64]
[13:07:12] [Server thread/WARN]: [Prison] Task #102 for Prison v2.1.0.1 generated an exception
java.lang.NullPointerException
	at me.sirfaizdat.prison.ranks.BalanceChangeListener$1.run(BalanceChangeListener.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-899f5ee-1092acb]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]

**Comment by SirFaizdat** [comment]
You need Vault for this plugin to function properly. Use the latest version of Vault and see if that helps.
