### ISSUE TITLE
Error when trying to demote user from console, promoting not working at all

### ISSUE THREAD

**Issue by Lahemees47** [SirFaizdat/Prison#69]
Edit: Those commands work when sent by an ingame player, but not from console.

I was trying to promote user from console with /prisonranks promote username, but it didn't do anything. Then I tried to demote that user and it gave me that error:

[14:24:25 INFO]: [Prison] There was an error handling command prisonranks. Reason: org.bukkit.craftbukkit.v1_8_R1.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
[14:24:25 INFO]: [Prison] More info:
[14:24:25 WARN]: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R1.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
[14:24:25 WARN]:        at me.sirfaizdat.prison.ranks.cmds.CmdDemote.execute(CmdDemote.java:22)
[14:24:25 WARN]:        at me.sirfaizdat.prison.core.Command.run(Command.java:75)
[14:24:25 WARN]:        at me.sirfaizdat.prison.core.AbstractCommandManager.onCommand(AbstractCommandManager.java:48)
[14:24:25 WARN]:        at me.sirfaizdat.prison.ranks.cmds.RanksCommandManager.onCommand(RanksCommandManager.java:69)
[14:24:25 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:24:25 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:24:25 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[14:24:25 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:631)
[14:24:25 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353)
[14:24:25 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317)
[14:24:25 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[14:24:25 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[14:24:25 WARN]:        at java.lang.Thread.run(Thread.java:744)
[14:24:25 INFO]: There was an error in starting ranks. Check the console for details.

**Comment by SirFaizdat** [comment]
Yeah, you need to do all that from in-game.

**Comment by Lahemees47** [comment]
But would it be possible to do it from console? That would be great.
