### ISSUE TITLE
Won't Load with Spigot 1.8.3

### ISSUE THREAD

**Issue by iampyrex** [SirFaizdat/Prison#74]
[23:34:13] [Server thread/ERROR]: Could not load 'plugins/Prison-2.1.2a.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/sirfaizdat/prison/core/Prison : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:199) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.UnsupportedClassVersionError: me/sirfaizdat/prison/core/Prison : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_75]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_75]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_75]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_75]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_75]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_75]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_75]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_75]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_75]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_75]
        at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-5cb9b70]
        ... 6 more

**Comment by iampyrex** [comment]
2.1.1 Doesn't work properly either.

**Comment by iampyrex** [comment]
Fixed after recompiling with Java 1.7

**Comment by DMP9-MC** [comment]
Yeah you need Java 7 or over to get a working 1.8.3 build. TotallyALF5 kindly posted a JAR file of Spigot 1.8:

http://dmp9software.co.uk/MC-SRV-API/Spigot/spigot-1.8.jar
