### ISSUE TITLE
/pranks add A 0 causing an internal error

### ISSUE THREAD

**Issue by calvin201** [SirFaizdat/Prison#86]
[21:50:53] [Server thread/INFO]: CalvinLove issued server command: /pranks add A 0
[21:50:53] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pranks' in plugin Prison v2.1.4-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionManager.getGroupList()Ljava/util/List;
	at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getGroups(Permission_PermissionsEx.java:372) ~[?:?]
	at me.sirfaizdat.prison.ranks.Ranks.isRank(Ranks.java:537) ~[?:?]
	at me.sirfaizdat.prison.ranks.cmds.CmdAddRank.execute(CmdAddRank.java:29) ~[?:?]
	at me.sirfaizdat.prison.core.Command.run(Command.java:75) ~[?:?]
	at me.sirfaizdat.prison.core.AbstractCommandManager.onCommand(AbstractCommandManager.java:48) ~[?:?]
	at me.sirfaizdat.prison.ranks.cmds.RanksCommandManager.onCommand(RanksCommandManager.java:83) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	... 15 more
[21:50:59] [Server thread/INFO]: CalvinLove issued server command: /pranks add A 0
[21:50:59] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pranks' in plugin Prison v2.1.4-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionManager.getGroupList()Ljava/util/List;
	at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getGroups(Permission_PermissionsEx.java:372) ~[?:?]
	at me.sirfaizdat.prison.ranks.Ranks.isRank(Ranks.java:537) ~[?:?]
	at me.sirfaizdat.prison.ranks.cmds.CmdAddRank.execute(CmdAddRank.java:29) ~[?:?]
	at me.sirfaizdat.prison.core.Command.run(Command.java:75) ~[?:?]
	at me.sirfaizdat.prison.core.AbstractCommandManager.onCommand(AbstractCommandManager.java:48) ~[?:?]
	at me.sirfaizdat.prison.ranks.cmds.RanksCommandManager.onCommand(RanksCommandManager.java:83) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	... 15 more
[21:51:01] [Server thread/INFO]: CalvinLove issued server command: /pranks add A 0
[21:51:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pranks' in plugin Prison v2.1.4-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionManager.getGroupList()Ljava/util/List;
	at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getGroups(Permission_PermissionsEx.java:372) ~[?:?]
	at me.sirfaizdat.prison.ranks.Ranks.isRank(Ranks.java:537) ~[?:?]
	at me.sirfaizdat.prison.ranks.cmds.CmdAddRank.execute(CmdAddRank.java:29) ~[?:?]
	at me.sirfaizdat.prison.core.Command.run(Command.java:75) ~[?:?]
	at me.sirfaizdat.prison.core.AbstractCommandManager.onCommand(AbstractCommandManager.java:48) ~[?:?]
	at me.sirfaizdat.prison.ranks.cmds.RanksCommandManager.onCommand(RanksCommandManager.java:83) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	... 15 more
[21:51:40] [Server thread/INFO]: [0;31;22mPrison [0;37;22m> [m[0;31;1mPlease specify a command.[m
[21:51:40] [Server thread/INFO]: [0;33;22m==============[0;31;1m[[0;32;22mRanks[0;31;1m][0;33;22m==============
[0;37;22m<> = Required argument    [] = Optional argument
[0;33;22m/prisonranks add [0;33;22m<rank> <price> [prefix]  [0;32;22m-[0;31;1m Adds a rank to Ranks.
[0;33;22m/prisonranks remove [0;33;22m<rank>  [0;32;22m-[0;31;1m Removes a rank from Ranks.
[0;33;22m/prisonranks promote [0;33;22m<user>  [0;32;22m-[0;31;1m Promote another user, free of charge.
[0;33;22m/prisonranks demote [0;33;22m<user>  [0;32;22m-[0;31;1m Demote another user. NO REFUNDS!
[m
[21:51:43] [Server thread/INFO]: [0;31;22mPrison [0;37;22m> [m[0;31;1mNot enough arguments. [0;33;22mProper usage: [0;33;22m/prisonranks add [0;33;22m<rank> <price> [prefix] [m
[21:51:48] [Server thread/INFO]: [0;31;22mPrison [0;37;22m> [m[0;31;1mNot enough arguments. [0;33;22mProper usage: [0;33;22m/prisonranks add [0;33;22m<rank> <price> [prefix] [m
[21:51:53] [Server thread/WARN]: Unexpected exception while parsing console command "pranks add A 0"
org.bukkit.command.CommandException: Unhandled exception executing command 'pranks' in plugin Prison v2.1.4-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionManager.getGroupList()Ljava/util/List;
	at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getGroups(Permission_PermissionsEx.java:372) ~[?:?]
	at me.sirfaizdat.prison.ranks.Ranks.isRank(Ranks.java:537) ~[?:?]
	at me.sirfaizdat.prison.ranks.cmds.CmdAddRank.execute(CmdAddRank.java:29) ~[?:?]
	at me.sirfaizdat.prison.core.Command.run(Command.java:75) ~[?:?]
	at me.sirfaizdat.prison.core.AbstractCommandManager.onCommand(AbstractCommandManager.java:48) ~[?:?]
	at me.sirfaizdat.prison.ranks.cmds.RanksCommandManager.onCommand(RanksCommandManager.java:83) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-fdc1440-53fac9f]
	... 8 more
[21:54:55] [Server thread/INFO]:

When i try set up a rank using /prank its come up saying there has been an internal error but it has does it with every rank plugin i have tried...

**Comment by SirFaizdat** [comment]
Please update your Java version to 1.7.

**Comment by calvin201** [comment]
okay thank you

**Comment by SirFaizdat** [comment]
Did that work?

**Comment by BlackKnightNick** [comment]
okay, so I have this same problem, but it doesn't have an error; it says, "That rank does not exist!"

**Comment by SirFaizdat** [comment]
You must create the rank in your permissions plugin first.

**Comment by BlackKnightNick** [comment]
Thank you!!!
