### ISSUE TITLE
Internal Error Occured

### ISSUE THREAD

**Issue by ChickenNuggetNG** [SirFaizdat/Prison#90]
I tried making a rank, but the same thing occurs. I am using PermssionsEx. I don't know if that's the problem. If it is, I am going to be very sad because I have no idea how to use other permissions plugins. It says "Internal error occurred", and I tried removing PermissionsEx, but it said "The rank does not exist." I really don't want to switch permissions plugins.

**Comment by SirFaizdat** [comment]
By "the same thing occurs", are you referring to issue #82? If so, please ensure that you have Vault and WorldEdit installed. If you do, there should be an error message in the console (it will look like a ton of random words and numbers). Can you please send me that error message (stack trace) in it's entirety?

Thanks :)

**Comment by ChickenNuggetNG** [comment]
10.10 14:19:27 [Server] INFO ... 15 more
10.10 14:19:27 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO at me.sirfaizdat.prison.ranks.cmds.RanksCommandManager.onCommand(RanksCommandManager.java:83) ~[?:?]
10.10 14:19:27 [Server] INFO at me.sirfaizdat.prison.core.AbstractCommandManager.onCommand(AbstractCommandManager.java:48) ~[?:?]
10.10 14:19:27 [Server] INFO at me.sirfaizdat.prison.core.Command.run(Command.java:75) ~[?:?]
10.10 14:19:27 [Server] INFO at me.sirfaizdat.prison.ranks.cmds.CmdAddRank.execute(CmdAddRank.java:29) ~[?:?]
10.10 14:19:27 [Server] INFO at me.sirfaizdat.prison.ranks.Ranks.isRank(Ranks.java:537) ~[?:?]
10.10 14:19:27 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getGroups(Permission_PermissionsEx.java:372) ~[?:?]
10.10 14:19:27 [Server] INFO Caused by: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionManager.getGroupList()Ljava/util/List;
10.10 14:19:27 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
10.10 14:19:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:672) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
10.10 14:19:27 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
10.10 14:19:27 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
10.10 14:19:27 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'prisonranks' in plugin Prison v2.1.4-SNAPSHOT
10.10 14:19:27 [Server] ERROR null

**Comment by ChickenNuggetNG** [comment]
there you go

**Comment by ChickenNuggetNG** [comment]
@SirFaizdat

**Comment by SirFaizdat** [comment]
What is your Java version? You must be running Java 1.7 or later to use Prison. If you have a server hosting provider, send them a ticket asking which Java version you have.

**Comment by ChickenNuggetNG** [comment]
yes i have all of this 1.8.8 my game version is 1.8.8 everything is the latest version

**Comment by SirFaizdat** [comment]
The only thing I can think of is that either Java or PermissionsEx is outdated. Please ensure that these are indeed the latest version.

**Comment by SirFaizdat** [comment]
Closing for inactivity in 36 hours.
